---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: APPNAME
  namespace: NAMESPACE
  labels:
    app: APPNAME
spec:
  replicas: REPLICAS
  minReadySeconds: MINREADYSECONDS
  revisionHistoryLimit: REVISIONHISTORYLIMIT
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: APPNAME
  template:
    metadata:
      labels:
        app: APPNAME
    spec:
      imagePullSecrets:
        - name: aliyun-secret
      containers:
      - name: APPNAME
        image: IMAGE_PATH
        imagePullPolicy: Always
        env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        ports:
        - containerPort: PORT
        volumeMounts:
         - name: nfs-volume
           mountPath: /mnt/wwwroot/source
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: PVC_NAME